version: "3.7"
# Ambiente de desarrollo local
# 1) Debe cambiar las rutas de los volumes de cada servicio
# 2) Ejecutar docker-compose -f docker-compose-dev.yml up ui

services:
  ui:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: npm start

